// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRq11yswbdlnD2gTyDo1eKZfm8wNoBgyc',
    appId: '1:881562948827:android:9733c024306301969968fe',
    messagingSenderId: '881562948827',
    projectId: 'mynew-27e56',
    storageBucket: 'mynew-27e56.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9FQ-E2JvpfSY8Ti5G9JdhMMubEVDWw1U',
    appId: '1:881562948827:ios:0a43cf444c15e9799968fe',
    messagingSenderId: '881562948827',
    projectId: 'mynew-27e56',
    storageBucket: 'mynew-27e56.appspot.com',
    iosClientId: '881562948827-v89a691qengpqa7b4foo06kiidc41ip1.apps.googleusercontent.com',
    iosBundleId: 'com.kiishi.mynew',
  );
}
